### ISSUE TITLE
RemoteDebugManager Excluded from EVSWorker

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.EVS#10]
Is the RemoteDebugManager.cs intentionally excluded from the project? If yes, do we need to keep it?

![image](https://user-images.githubusercontent.com/938023/44424973-805e8180-a53f-11e8-9c86-3f6145f8322b.png)

**Comment by hismightiness** [comment]
Any update, @ashishpd ?

**Comment by zyhfish** [comment]
the files should able to be removed if its not included in any project.
