### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by david-poindexter** [dnnsoftware/Dnn.EVS#11]
## Description 
Currently there are no issue templates for this repo.

## Steps to reproduce
Click **New Issue** button on GitHub repo.

## Current result
No issue templates are used.

## Desired result
The user should be able to choose from several issues types (e.g., **Bug Report**, **Feature Request**, **Help & Other Questions**)

## Affected version
* [x] ?.?.?

**Comment by hismightiness** [comment]
Any update, @ashishpd ?
