### ISSUE TITLE
Update GitHub repo Description to include keywords

### ISSUE THREAD

**Issue by nvisionative** [dnnsoftware/Dnn.EVS#2]
Please update the this repo's description to include, at minimum, the keywords **DNN** and **DotNetNuke**.  Currently **DNN's** is used, which throws off GitHub search attempts.  The recommended way is to use something like:
`DNN (formerly DotNetNuke) Extension Verification Service`

**Comment by tpluscode** [comment]
Done. Also added website URL

**Comment by nvisionative** [comment]
Thanks @tpluscode !
