### ISSUE TITLE
Extra Unused Folders in ProcessStorePackages

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.EVS#7]
There are no files in these folders (image below).  Do the folders have a purpose?

![image](https://user-images.githubusercontent.com/938023/44424541-3cb74800-a53e-11e8-8e49-705077d2b776.png)

**Comment by hismightiness** [comment]
Any update, @ashishpd ?

**Comment by zyhfish** [comment]
its empty as well in the original repo, IMO it should be ok to clear if you want.
