### ISSUE TITLE
DNN 9.x Missing from EVSWorker

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.EVS#8]
Is there supposed to be a DNN 9.xx collection of provider files here?

![image](https://user-images.githubusercontent.com/938023/44424707-c830d900-a53e-11e8-8d78-1f7574a8287c.png)

**Comment by hismightiness** [comment]
Any update, @ashishpd ?

**Comment by zyhfish** [comment]
it should be good to keep it as is for now, the files can be added if need in the future, thx
