### ISSUE TITLE
PetaPoco Excluded from EVSAppController

### ISSUE THREAD

**Issue by hismightiness** [dnnsoftware/Dnn.EVS#9]
Is the PetaPoco.cs intentionally excluded from the project?  If yes, do we need to keep it?

![image](https://user-images.githubusercontent.com/938023/44424858-2a89d980-a53f-11e8-8097-3b720a477543.png)

**Comment by hismightiness** [comment]
Any update, @ashishpd ?

**Comment by zyhfish** [comment]
the code files should able to be removed if it not included in any project.
